### ISSUE TITLE
no content summaries

### ISSUE THREAD

**Issue by wguo1990** [panr/hugo-theme-hello-friend#100]
`<!--more-->` is not working when placed in the end of .md

**Comment by wguo1990** [comment]
is not working when it was placed in the end of the article.

**Comment by wguo1990** [comment]
"" is not working when placed in the end of .md

**Comment by panr** [comment]
Have you tried `description` prop in front matter?

**Comment by wguo1990** [comment]
Yes, no problem with `description`. 

I found `<!--more-->` works only when it was placed in the middle of the post. I tried other themes and there is no issues when putting `<!--more-->` in the end. Do you happen to know the reason?

**Comment by panr** [comment]
Probably because I made it that way 😬
