### ISSUE TITLE
[Improvement] Avoid Invisible text during loading (FOIT)

### ISSUE THREAD

**Issue by subinsv** [panr/hugo-theme-hello-friend#101]
I ran google page insight on my blog that uses this theme.

Google result suggests to avoid invisible text during loading by using `font-display: swap` property.

Reference: https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown

Can we add this improvement.
I can change the fonts.css and can create an PR if required.

**Comment by panr** [comment]
Good idea! 👍

**Comment by subinsv** [comment]
Opened an PR #102
