### ISSUE TITLE
image alignment and figcaption tag issue.

### ISSUE THREAD

**Issue by hazar-e** [panr/hugo-theme-hello-friend#11]
images and figcaptions are left aligned. I want to align images to center. The changes I made at css files did not affect. can someone help?

**Comment by panr** [comment]
Hi @hazar-e 👋🏻 I’ve just added a shortcode `{{ < image > }}` to help you with this issue. Shortcode has one required prop `src` just like default html element and few optional: `alt` (String), `position`(left | center | right) and `style` (for any additinal CSS inline styling props).

If you don’t know what shortcodes are, please read Hugo docs 
https://gohugo.io/content-management/shortcodes/

**Comment by hazar-e** [comment]
Hi @panr Image now centered but the **title** does not appear because [<`img`>](https://www.w3schools.com/tags/tag_img.asp)  tag does not have the title attribute.

your shortcode input
`{{< image src="/img/spot.gif" position="center" title="This is title" >}}`

html output
`<img src="/img/spot.gif" class="center">`

actually it should be this way --> [https://www.w3schools.com/tags/tag_figcaption.asp](https://www.w3schools.com/tags/tag_figcaption.asp)

**Comment by panr** [comment]
Oh, now I see. I made `image` shortcode, not `figure`. I'll fix it today ;-)

**Comment by panr** [comment]
@hazar-e 

Ok, now you have `figure` shortcode with props:
- src (**required**)
- alt (image alt)
- position (left is default; figure position `left | center | right`)
- style (image additional styling)
- caption (figure caption)
- captionPosition (center is default; but you can set it to `left | center | right`)
- captionStyle (caption additional styling)

**Comment by hazar-e** [comment]
@panr thank you for your interest. Good work.
