### ISSUE TITLE
How to create "about" menu

### ISSUE THREAD

**Issue by victorsnk** [panr/hugo-theme-hello-friend#113]
Good morning, sir.

I think I'm going crazy. I managed to create in the menu the section "obout" but I don't know how to make it detect the about page.

```
[languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "about"
          url = "/about"

  [[languages.en.menu.main]]
          identifier = "blog"
          name = "formación"
          url = "/posts"
```

![Captura de pantalla 2019-12-08 a las 10 33 33](https://user-images.githubusercontent.com/32032710/70387512-36084a80-19a6-11ea-838c-184e8795c73a.png)

The web site is http://victoraf.gitlab.io

**Comment by aormsby** [comment]
I remember playing around with my menus a bit when I started, so perhaps I can help while I fly through and check my notifications. I'm unclear on the issue, though. Is it that the menu doesn't appear? Or that clicking the link doesn't go to the right place? Or something else?

**Comment by victorsnk** [comment]
SOLVED! Thank you very much.
