### ISSUE TITLE
How create a new icons?

### ISSUE THREAD

**Issue by victorsnk** [panr/hugo-theme-hello-friend#116]
Hi! How can I create a new social icon? I need to put an any "podcast" icon and an any "camera" icon. Thank you very much.

**Comment by huyhoang8398** [comment]
i use a raw html short code, you can check in https://dohoang.me/about/

**Comment by victorsnk** [comment]
Sorry I don’t understand how can I do it

**Comment by panr** [comment]
Hi @victorsnk you're referring to wrong repo. You should ask for that in https://github.com/rhazdon/hugo-theme-hello-friend-ng which is fork of my theme where you have all "social stuff"...
