### ISSUE TITLE
About page is showing as a post page

### ISSUE THREAD

**Issue by Zjemm** [panr/hugo-theme-hello-friend#118]
Hi There,

I noticed that when i use your theme and examplesite content.
the about page is showed as a post page, and thus showing the "Read other posts" section and button.

but on the demo site linked on the git page, this is not the case. there the about page shows as a single page,

how can i recreate that? as i want the about page to show without the  "Read other posts" section and button, like a single page

**Comment by panr** [comment]
Where do you keep `about.md` file?

**Comment by Zjemm** [comment]
it's in the content folder. 

exactly like:
https://github.com/panr/hugo-theme-hello-friend/tree/master/exampleSite/content

**Comment by panr** [comment]
So... did you add `type` parameter to front matter? If so, what it is?

**Comment by Zjemm** [comment]
What do you mean by that? Do you have an example?

**Comment by panr** [comment]
```
[...]
type = "post"
[...]
```

**Comment by Zjemm** [comment]
no there was no type in the example's site about.md

+++
title = "About"
date = "2019-01-25"
author = "Radek"
+++


but i guess making it a type post does make it a post and therfor still show the "Read other posts" section and button

**Comment by Zjemm** [comment]
i'm using hugo 0.60 (latest version i think)
so maybe something changed? 
i you run a new page based on this theme downloaded from git and used the examplesite content.
does it do the same output as the demo site? or do you see the same as me, where the about page and the showcase page show up as posts in stead of single pages?

**Comment by panr** [comment]
> i tried:
> type = "page"
> but doesn't seem to affect anything

No, no. There shouldn't be any `type = "post"`. I asked because that could do the issue you have... So without adding anything to your `about.md` that's weird you see it as a `post` (only posts have **others** navigation)...

I think I need to see your file structure and `config` file...

**Comment by Zjemm** [comment]
[tree.txt](https://github.com/panr/hugo-theme-hello-friend/files/3979166/tree.txt)

[config.txt](https://github.com/panr/hugo-theme-hello-friend/files/3979172/config.txt)

here is the output of tree, and the config file.

i wonder if you can replicate it with what i described in my previous post

**Comment by panr** [comment]
Oh may... You were right, something broke after updating to latest Hugo. I'm on it ;-)

**Comment by panr** [comment]
Fixed it quickly. Should work fine, but I have to think how to handle this case better in the near future. 

Please let me know, if it works ;-)

**Comment by Zjemm** [comment]
Oh cool, I’ll try and let you know

**Comment by Zjemm** [comment]
yes it works now.
thanks for looking into it. love the theme

great work

**Comment by panr** [comment]
Cool! You're welcome 😎
