### ISSUE TITLE
Configuration parameter for dark/light mode

### ISSUE THREAD

**Issue by alexkieling** [panr/hugo-theme-hello-friend#12]
I'd like to have the light mode as default. Would be possible to add a configuration parameter to set that?

**Comment by panr** [comment]
@alexkieling not right now, but it's a good idea to add this as an option to `config.toml`. I'll add it soon ;-)

**Comment by alexkieling** [comment]
Awesome! Great work, by the way.

**Comment by panr** [comment]
@alexkieling done 🎉 Now you can set your default theme in config.toml like this https://github.com/panr/hugo-theme-hello-friend/blob/master/exampleSite/config.toml#L11

Default theme works until user changes it, then preferred theme is default (as localStorage key)
