### ISSUE TITLE
Add support for auto detecting dark/light

### ISSUE THREAD

**Issue by Benjamin-Lee** [panr/hugo-theme-hello-friend#126]
See https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme for more.

**Comment by declarativephoenix** [comment]
@panr any reason for closing this issue without any comments?

**Comment by panr** [comment]
Because the theme color is set by the author of a blog / site. But we can make it work like if there's no theme color is set, the theme is inherited from the OS.

**Comment by declarativephoenix** [comment]
> But we can make it work that if there's no theme color set, the theme is inherited from the OS..
Do you mean to say this happens already or that this hasn't been implemented but can be?

**Comment by panr** [comment]
The latter.

**Comment by aormsby** [comment]
Or there could be an explicit "auto" setting for authors. I'm not really pushing for any implementation, but I'm always a fan of being explicit. :)
