### ISSUE TITLE
Preview on the main page is not displayed (except cover image)

### ISSUE THREAD

**Issue by x4team** [panr/hugo-theme-hello-friend#127]
Hello. 
There is no post text on the main page in the preview.
**My page:**

```
---
title: "Second"
date: "2020-01-09T21:32:50Z"
publishDate: "2020-01-09T21:32:50Z"
cover: "https://s1.1zoom.me/b5050/879/277488-Sepik_1680x1050.jpg"
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```
Thank you!

**Comment by panr** [comment]
What's your Hugo version? Should be at least 57.

**Comment by x4team** [comment]
> What's your Hugo version? Should be at least 57.

Hugo Static Site Generator v0.62.2-83E50184 linux/amd64 BuildDate: 2020-01-05T18:51:38Z

**Comment by x4team** [comment]
I tested in MacOS  and Ubuntu - hugo old version 0.60, to no avail

**Comment by x4team** [comment]
**SOLVED**!!!
Decided everything option **description** in the post settings.  She is responsible for the preview of the text of the post on the main page.

---
title: "Second"
date: "2020-01-09T21:32:50Z"
publishDate: "2020-01-09T21:32:50Z"
cover: "https://s1.1zoom.me/b5050/879/277488-Sepik_1680x1050.jpg"
description: "TEXT PREVIEW"
---
Lorem...
