### ISSUE TITLE
How to: icons in main menu

### ISSUE THREAD

**Issue by bhehar** [panr/hugo-theme-hello-friend#130]
Hello, 

How can I add icons for social links such as LinkedIn in the main menu?

**Comment by aormsby** [comment]
There are a few different ways, but placement depends on where you want them. For example, I added an icon near the end of the file `layouts/partials/header.html` just by inserting another small partial that I built for the purpose.

An alternative method would be to add a 'LinkedIn' item to your menu in the config.toml file that simply links to your page. Or if you want to keep your links them agnostic, I also have an example on my site where I just added some into page content as a contact list on [my About page](https://aormsby.github.io/about/). My site is unfinished currently, but hopefully you get something out of the examples.

A little experimentation may be needed to find exactly where you would want to put your icons and links. 🙂

**Comment by bhehar** [comment]
I was thinking about adding a few links in the header like you have the ko-fi link, but having it in the About pages does look a lot cleaner. 

I'm not familiar with HUGO or webdev,  could you point me in the right direction to a tutorial or article.

**Comment by aormsby** [comment]
I wish I could! Unfortunately, I haven't found many strong resources either. The Hugo docs are helpful, but only after you're more familiar with things, which isn't ideal. I've spent time in the last few months just trying things out through trial and error so I have a better understanding of the system now, but there are still plenty of things I haven't figured out. I'm considering starting a repo for Hugo code snippets to help out with things like this, but who knows if that'll catch on? It's tough at first, but you'll get the hang of it.

**Comment by bhehar** [comment]
Well, thank you for the inspiration. I've looked around some more and I think I have an idea of how to do it.  I would love to have those code snippets, I hope you make them!
