### ISSUE TITLE
Content folders other than "posts" breaks theme

### ISSUE THREAD

**Issue by seraxis** [panr/hugo-theme-hello-friend#135]
Using any other contentTypeName other than "posts" results in the theme not picking up that folder: https://github.com/panr/hugo-theme-hello-friend/blob/184a74ceb294e91ddaad2ffc15e99258bad69698/layouts/_default/list.html#L3

Is there a reason for this behaviour when it could be generic?

**Comment by panr** [comment]
You can set this in the config file https://github.com/panr/hugo-theme-hello-friend
The reason for that is to help set a main content type for the index page without any slugs or permalinks.

I’m open to any suggestions 🤓

**Comment by valdecircarvalho** [comment]
Hi @panr 
I'm trying to add a quote/tweet post type without the "Read More" link. An example is this page
http://themes.wplook.com/?ref=3&themename=morning-time
Any ideas on how to change this in your theme?

**Comment by panr** [comment]
@valdecircarvalho you can use this param https://github.com/panr/hugo-theme-hello-friend#how-to-hide-read-more-button (I just added it)

**Comment by BharatKalluri** [comment]
Hi @panr ,

If I have a folder called posts, and another folder called projects (which contains a bunch of .md files, each file denoting a project). I am trying to get a list page for projects as well (similar to posts) . Is there any way I can achieve this using hello-friend?

**Comment by guilhermesteves** [comment]
Hi @BharatKalluri, inside your **projects** folder, create a file called `_index.md` with the content:

```

+++
title = "Projects"
layout = "list"
url = "/projects"
type = "projects"
+++
`
``
