### ISSUE TITLE
prepended & extended_head does not work for templated content

### ISSUE THREAD

**Issue by tryffel** [panr/hugo-theme-hello-friend#139]
It would be nice to allow configuring per-page head definition. Reason for this is to allow embedding 
<meta name=go-import> redirect for some pages. I created prepended_head.html as:
```html
{{ if isset .Params "goimportpackage" }} 
    <meta name="go-import" content="{{ .Params.GoImportPackage }} git {{ .Params.GoImportUrl }}">
{{ end }}
```
And then declare goimportpackage & url inside each document.
As a result, this **meta tag is inside body, not head**. I tried replacing partial with static content (```<meta name="test">```) and it works as expected though.

**Comment by panr** [comment]
Hmm... Tried it and `<meta>` loads inside `<head>` 🤔

**Comment by tryffel** [comment]
Yeah, cannot reproduce anymore, my bad. Closing.
