### ISSUE TITLE
Hugo 0.54 version issue w/ Netlify 

### ISSUE THREAD

**Issue by gerardsimons** [panr/hugo-theme-hello-friend#145]
Hello friends!

Awesome theme, just a little issue : I am trying to run it on Netlify but it raises an error

`HELLO-FRIEND theme does not support Hugo version 0.54.0`

Any idea on how to fix this? Is it hard to upgrade it to this version or higher?

**Comment by panr** [comment]
The theme needs at least Hugo 0.57.0 ang higher, so you have to update the version on your Netlify server ;-)

**Comment by gerardsimons** [comment]
@panr : yeah sorry that was more on the netlify end, nothing to do with you or your theme, my bad. Thanks for the awesome theme by the way, I donated you a coffee, enjoy :-)

https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify
