### ISSUE TITLE
Cover image may not appear in RSS reader - any ideas?

### ISSUE THREAD

**Issue by aormsby** [panr/hugo-theme-hello-friend#147]
So the cover system is working great, but I've noticed that my cover images do not show up when I'm reading a post in my RSS reader.

In the RSS list view, I get whatever photo is in the generated OpenGraph card (should be the cover if it works right, but may not be). When I open to the reader's post view, there is no cover image. I guess this is because `.Content` for the RSS feed does not include the cover image, which is set in the front matter.

Do you think there is any way in the theme to add the cover photo into the RSS feed data? My first guess would be that this is RSS-related, not theme-related (which I'm looking into over here), but I wanted to see if you had any ideas on your end.

**Comment by panr** [comment]
I think you can achieve this by creating `rss.xml` template inside `layouts` dir and attach it in `head.html` 🤔

**Comment by aormsby** [comment]
Yeah, modifying `rss.xml` seems to be the only way to explicitly add the cover post into the feed data. I've been playing with it some (rss validation can be tricky!), and I've been able to use the same cover params you check for in the front matter to add those cover images into the RSS feed. So that's great!

However, I've also been looking into Hugo's internal social media templates (Twitter cards, OpenGraph stuff), and I noticed they're automatically grabbing cover images by [matching specific filenames](https://github.com/gohugoio/hugo/blob/25a6b33693992e8c6d9c35bc1e781ce3e2bca4be/tpl/tplimpl/embedded/templates/twitter_cards.html#L5-L10) in page bundles. I may use that same method in my RSS feeds for cases when the front matter cover params aren't specified. It matches up with Hugo's other internals nicely.

I'm wondering this:
- As an addition to your theme, would you be interested in using the customized `rss.xml` I'm now working on?
- Would you also be interested in adding the resource matching functionality to your list and single templates as a fallback way to find cover images automatically if the cover params aren't specified on a page?

I'd be happy to send a PR for both if that's something you'd like. 🙂

**Comment by panr** [comment]
Sure, I like the idea 😍

**Comment by aormsby** [comment]
RSS PR #148 made!

For the automatic cover image search, I wrote a simpler version of what is found in the internal social media template here:

https://github.com/gohugoio/hugo/blob/25a6b33693992e8c6d9c35bc1e781ce3e2bca4be/tpl/tplimpl/embedded/templates/twitter_cards.html#L5-L7

I can do that same thing for list and single pages, but I honestly don't know if it's necessary. Your cover params are pretty nice and very straightforward. However, having the automatic image grab might be a good backup, perhaps if someone is changing themes. Happy to keep going with that if you'd like, just let me know.
