### ISSUE TITLE
can't set hiddenFromHomePage

### ISSUE THREAD

**Issue by eallion** [panr/hugo-theme-hello-friend#153]
when i set `hiddenFromHomePage: true` ,but that post is not hidden.

**Comment by panr** [comment]
Hi @eallion, what is `hiddenFromHomePage` prop? I don't recall that the theme supports it...

**Comment by hg8** [comment]
You can use `type = "archive"` which achieve the same result.

**Comment by eallion** [comment]
> Hi @eallion, what is `hiddenFromHomePage` prop? I don't recall that the theme supports it...

Hi, thanks for your reply!
When i post a new SHORT article , I don't want to see it in the main page, i want to hide it .
I found this this command whit Google, i thought it was a default feature，my bad.

**Comment by eallion** [comment]
> You can use `type = "archive"` which achieve the same result.

Thanks very much!

**Comment by guilhermesteves** [comment]
@eallion is it solved? Can you close the issue?

**Comment by eallion** [comment]
> @eallion is it solved? Can you close the issue?

OK thanks , I will find another way.
