### ISSUE TITLE
R language highlited

### ISSUE THREAD

**Issue by dsolito** [panr/hugo-theme-hello-friend#16]
Hello panr,

can you please add R as language in prism?

Thank you.

**Comment by dsolito** [comment]
Ha... doesn't see to work. Perhaps the Rmarkdown format is the cause?
Check here : www.davidsolito.com

**Comment by dsolito** [comment]
I don't see prism in my page header… I miss something?

**Comment by panr** [comment]
@dsolito have you tried wrapping R code like this:

```r
[code]
```

?

**Comment by dsolito** [comment]
I work with rstudio and what I understand is that it depends on the type of markdown document I use.
I work in .rmd format and blogdown (package to build the site) generate the html.

But if you look at the html page, the code is inside <pre><code> … </code></pre>

Details : 

You cannot execute any R code in a plain Markdown document, whereas in an R Markdown document, you can embed R code chunks (```{r}). However, you can still embed R code in plain Markdown using the syntax for fenced code blocks ```r (note there are no curly braces {}). Such code blocks will not be executed and may be suitable for pure demonstration purposes. Below is an example of an R code chunk in R Markdown:

```{r cool-plot, fig.cap='A cool plot.'}
plot(cars, pch = 20)  # not really cool
```
And here is an example of an R code block in plain Markdown:

```r
1 + 1  # not executed
```

**Comment by panr** [comment]
@dsolito As far as I understand, R Studio is parsing markdown files differentely than Hugo, additionally Prism won’t catch `{r}` syntax out of the box... Maybe you should fork Prism library and modify it for your case 🤔

If I’m wrong and this could be issue with my theme code, please create PR with necessary modifications 😉
