### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by hotshot07** [panr/hugo-theme-hello-friend#167]
Hi,
How can I set my personal favicon?
I cannot find where to configure, and I didn't see the instruction in documentation.

**Comment by aormsby** [comment]
Ah yes, I remember I had to search for this a bit as well. It might be a good idea to add a note to the README somewhere. These are the paths where the theme finds your icon(s), from `layouts/partials/head.html`. 🙂 

![Screen Shot 2020-06-28 at 22 08 25](https://user-images.githubusercontent.com/1312251/85968915-e615c300-b98b-11ea-900a-b38c2dedf98b.png)

**Comment by hotshot07** [comment]
Hi @aormsby, I've put the favicon.png in both 'blog/static/img/' and 'blog/themes/hello-friend/static/img' but it still isn't detecting it. Also, any changes I make to the hello-friend theme isn't being detected (I have it as a submodule). Any idea what I might be doing wrong? thanks :)

**Comment by aormsby** [comment]
Okay, so let me clarify one thing first - is `blog/` an actual subfolder in your project? Or are you referring to the root project folder? That `/static` folder where you would place your images is the one in the project's root folder. (Adding them to the theme data will do nothing here.)

The theme being a submodule shouldn't matter here.

**Comment by hotshot07** [comment]
This is my directory structure, blog is my root dir, yes.
![Screenshot 2020-06-29 at 23 23 25](https://user-images.githubusercontent.com/31933830/86061935-93a5d680-ba5f-11ea-80ea-e90ca23d4a0b.png)
This isn't working for some strange reason :(

**Comment by panr** [comment]
Hi, the path to favicon should be `static/img/favicon.png` (I see that you have one in the right place). So I guess two things:
- browser cache
- restart hugo server with `hugo server --disableFastRender`

Just tested replacing (missing, I know...) favicon and worked fine on my setup.

**Comment by hotshot07** [comment]
Hi, the above solution didn't work for me as expected so I put the favcion in the root dir and added this line to themes/hello-friend/layouts/partials/head.html
`<link rel="icon" type="image/png" sizes="512x512" href="/favicon.png">`
It did the trick for me. Thank you :)
