### ISSUE TITLE
Suggestion : Don't push webpack dev builds to master branch assets !

### ISSUE THREAD

**Issue by adityatelange** [panr/hugo-theme-hello-friend#175]
People use the theme directly my cloning or as a submodule. Thus getting the assets as dev builds, having some unnecessary debug information in it.

Before pushing to master branch , run _production_ build with  [`npm run build`](https://github.com/panr/hugo-theme-hello-friend/blob/master/package.json#L9), without this the **assets** aren't _minified_ and takes up more **disk space** and **time** to load the pages.
Thank you.

**Comment by panr** [comment]
Why so many exclamation marks?

**Comment by adityatelange** [comment]
> Why so many exclamation marks?

just formatting nothing else.

**Comment by panr** [comment]
Got it. Fixed it. Thank you!
