### ISSUE TITLE
Error building site: TOCSS: failed to transform "scss/main.scss"

### ISSUE THREAD

**Issue by TheGroundZero** [panr/hugo-theme-hello-friend#176]
Hi all,

Today I pulled the latest changes to this repo, has been a while.

If I know want to run the hugo server, I get the following error:
```
$ hugo server
Built in 194 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
```

Any ideas on how to fix?

**Comment by panr** [comment]
Hmm... do you use my theme, or this one — https://github.com/TheGroundZero/hugo-theme-hello-friend-ng?

**Comment by TheGroundZero** [comment]
I was using yours.  

Deleted whole dir and submodule references and repulled repo.  
No error now, but quite a big change in layout.

Old  
![image](https://user-images.githubusercontent.com/2406013/88078420-c0d83700-cb7c-11ea-83a3-221000dd97c4.png)

vs New  
![image](https://user-images.githubusercontent.com/2406013/88078505-d6e5f780-cb7c-11ea-9eb4-5fca7d82e0a3.png)

**Comment by panr** [comment]
Not sure if this is the right repo that I'm linking here (https://github.com/TheGroundZero/hugo-theme-hello-friend-ng/commits/master) but it looks like you're using `hello-friend-ng`, which is a fork of my theme with a lot of changes.

**Comment by TheGroundZero** [comment]
My apologies.  
I am indeed running the fork.

**Comment by panr** [comment]
No problem ;-)
