### ISSUE TITLE
Archive layout

### ISSUE THREAD

**Issue by shawnyeager** [panr/hugo-theme-hello-friend#177]
Apologies in advance, but I've dug around and can't figure where the layout for /archive is defined. Compared to the rest of the design, the single-line centered layout seems a bit less than optimal.

Any pointers are appreciated. Thanks.

**Comment by panr** [comment]
https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/archive/list.html

**Comment by shawnyeager** [comment]
I was looking only in CSS. Should have looked here for clues. 🤦🏼‍♂️

Thanks.
