### ISSUE TITLE
Adding Bootstrap ruins current css

### ISSUE THREAD

**Issue by cindrmon1899** [panr/hugo-theme-hello-friend#179]
Good Day!

I wanna ask how can it be possible if there's a way for you to add bootstrap into this theme? Because when I am trying to add bootstrap, your css files are mostly overridden.

Thank you in advance

**Comment by panr** [comment]
How did you add it? Any code examples, diff, files you've modified?

**Comment by cindrmon1899** [comment]
all i did was add the bootstrap link into my extra_head.html:

`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">`
