### ISSUE TITLE
please help with 2.0 - confused about new setup process

### ISSUE THREAD

**Issue by aormsby** [panr/hugo-theme-hello-friend#185]
Hey, I see you made some sweet updates! Unfortunately, I'm *terrible* with node package management and need help integrating your work into my working repo. I'm a bit confused by what's needed during setup to run the new Pipes release.

So here's what you wrote in the README:

> The theme is using Hugo Pipes to handle Javascript and PostCSS files. This setup requires following npm packages:
>
> @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url
>
>Before you start, you have to install them (globally or locally).

So far, I went into the theme directory and I ran `npm install` to start. This doesn't seem to install the newly required babel and prism dependencies and perhaps a few other things I'm not seeing yet. So before I muck this up, my questions are:

- Am I supposed to install these in the site's root directory or in the theme directory? (ignoring the global option for the moment)
- Is it absolutely required to install these packages manually?
- If my understanding is correct, couldn't all the new package requirements be included in the `packages.json` file for easy install with `npm install`? Or is that a naive assumption?
- Is there any way to streamline this new setup and make it safer for node dummies like me?

I'm still loving the theme, man! Looking forward to figuring this out. Cheers. 🙂

**Comment by panr** [comment]
> So far, I went into the theme directory and I ran npm install to start.

This is unfortunately something that bothers me a lot. Hugo Pipes doesn't work like that, I thought they were but no ;-(

You have to run the command below in your root directory (not the theme directory as before):

```
npm i @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url
```

Then running the local `hugo server` should be enough. Please let me know if this works 🙏 

---

Direct answers:

> Am I supposed to install these in the site's root directory or in the theme directory? (ignoring the global option for the moment)

Site's root dir.

> Is it absolutely required to install these packages manually?

I'm afraid this is the only way 😭 Unless I don't know how to do it better 🤔 

> If my understanding is correct, couldn't all the new package requirements be included in the packages.json file for easy install with npm install? Or is that a naive assumption?

Yes, but as far as I understand Hugo Pipes runs from your site's root dir (thanks to `hugo server` or `hugo` commands), not the theme itself. I think it's necessary for the Hugo path lookup thing.

> Is there any way to streamline this new setup and make it safer for node dummies like me?

Updated README is the only idea I have at the moment ;-(

**Comment by aormsby** [comment]
What you say makes sense. I'm going to try what you recommended and let you know if it works out.

I wonder why Hugo doesn't add its own package file. What do you think about adding an extra "move to root" package file somewhere in the theme that users can move into the root directory and then install? It doesn't really solve the issue of having to take the extra steps, but at least there would be less chance of messing it up. Food for thought.

**Comment by aormsby** [comment]
Good News - installing the packages in root works!
Concerning News - My build time went from 2 seconds to 12. My site's really small. That can't be a good sign.

**Comment by aormsby** [comment]
I also generated some new assets on the build. Maybe this is expected. Just checking.

![Screen Shot 2020-08-12 at 21 23 05](https://user-images.githubusercontent.com/1312251/90087296-056d7300-dce2-11ea-885e-c2630c5c46ff.png)

**Comment by panr** [comment]
> What do you think about adding an extra "move to root" package file somewhere in the theme that users can move into the root directory and then install?

Could you elaborate on this?

> Concerning News - My build time went from 0.5 seconds to 12. My site's really small. That can't be a good sign.

I believe this happens only for the first time. When you're in watch mode it should be shorter.

> I also generated some new assets on the build. Maybe this is expected. Just checking.

Just saw this in my setup. Don't know why those files appear... 🤔 

---

Now I'm starting to think that moving the Hugo Pipes (probably) wasn't a good idea 🙈

**Comment by aormsby** [comment]
> Could you elaborate on this?

My thought was to create a `package.json` file for the user's root Hugo directory. You could make the file and add it to an extra folder in your theme. Then users could drag that file into their root and run `npm install` for a quick installation.

However, the only benefit would be that users wouldn't have to copy-paste all those packages from the README. I guess it's a little safer because you would include exactly what they needed to install in the package file. But they still have to do the manual installation and manage all that on their own outside the theme. I'm not sure it's a very helpful idea.

> I believe this happens only for the first time. When you're in watch mode it should be shorter.

Yes, watch mode is fine, but the slow build time stood out to me because Hugo is known for building even large sites very fast. I have a very small site right now, but my build time still increased by 2300% (0.5 -> 12 seconds). If I had a much larger site to build, this could be a problem.

For reference, here's my 2.0 build. Not a ton.

```
                   | EN   
-------------------+------
  Pages            |  61  
  Paginator pages  |   2  
  Non-page files   | 109  
  Static files     |  30  
  Processed images |   2  
  Aliases          |  13  
  Sitemaps         |   1  
  Cleaned          |   0  

Built in 13050 ms
```

> Now I'm starting to think that moving to the Hugo Pipes (probably) wasn't a good idea 🙈

Maybe, maybe not. I've also been thinking about implementing Pipes into my root since I have some things I maybe wanted to run through post-processing during the build. It honestly seems like a good idea overall since many of the processing steps you might normally do are supported by Pipes now. Buuut I don't really know what the best option is because I haven't spent much time looking into Pipes yet.

Something you might consider - I didn't setup Pipes and its dependencies in my root before now, which seems to be where the complications began. If a dev is already using Pipes features, then (I would guess) your updates to the theme would integrate smoothly into the existing workflow. But if they haven't set up anything for Pipes, then it requires changes to the dev's root. It sounds like a pain point to work out.

I wonder if a better approach would be to support Pipes processing _if it's already active in the root_, but fall back to the old way if it isn't. (Is that possible?) This would create a longer transition time from old to new and increase your amount of build support for a while, but it would also give you (and us users) more time to look into these questions that are coming up. And perhaps we'd find a way to smooth out the setup process as well.

By the way, I'm totally willing to look into this more with you. I'm interested in exploring these upgrades as well. Open to collab. 😉

**Comment by panr** [comment]
> I wonder if a better approach would be to support Pipes processing if it's already active in the root, but fall back to the old way if it isn't. (Is that possible?) 

Don't know how to detect it. On the other hand it looks too complicated and unnecessary...

I'm afraid that switching to Hugo Pipes was a mistake 😬 I'm considering going back to Webpack 🙉

**Comment by aormsby** [comment]
> I'm afraid that switching to Hugo Pipes was a mistake 😬 I'm considering going back to Webpack 🙉

Up to you, man. With what I know about Hugo Pipes (very little), it does seem like a good move overall, but perhaps it's premature. It might be a matter of stepping back, working out the finer details, and trying again.

**Comment by aormsby** [comment]
Haha wait a sec - For some reason, I thought Pipes was much more complex before I read some stuff about its uses. Now I see it's rather straightforward (at least in adding it to the layouts). If I'm getting this right, all you're trying to do is process CSS files (using PostCSS) and JS files (using Babel). It sounds simple, so it makes me wonder why this is turning out to be so difficult.

From what I saw in the changelog, you only added Pipes-related functionality to 2 files - `footer.html` and `head.html`. I saw you also removed nearly everything from your `package.json` to clean that up.

**Question 1 -** If you're only using PostCSS and Babel through Pipes, why remove all the other dependencies from `package.json`? I was confused by that.

**Question 2 -** Why specifically use Babel and PostCSS? Are there any Hugo built-in alternatives to some of what you're doing. For example, using [`resources.Minify`](https://gohugo.io/hugo-pipes/minification/) for minifying JS instead of minifying through Babel? I just wonder if there are alternatives to avoid using external packages for any of this stuff.

Forgive me, I'm looking into this for my own needs as well so I'm still trying to understand how to set up Pipes well. I'm going to try a few things and let you know if I find any improvements.

**Comment by aormsby** [comment]
Okay, this will be my last post on this for now. I think I need to chill after. I apologize for the semi-crazed ramblings.

I've found out a few things that have shifted my perspective on Pipes a little and also might answer a few questions we've had.

Screen Shot 2020-08-12 at 21 23 05
> ![Screen Shot 2020-08-12 at 21 23 05](https://user-images.githubusercontent.com/1312251/90087296-056d7300-dce2-11ea-885e-c2630c5c46ff.png)
1. **Extra Assets** - I think these are **fine**. They get generated on a build, and they're the processed versions of the css files that the head partial build with. `{{ $style.Permalink }}` is that output file.

2. **Longer Build Times** - I really think this is because processing with Pipes happens on **every** build. But before, I wasn't building the theme. You'd already done that and locked it down using yarn and webpack, so there was no processing to be done during a build. This resulted in super-fast builds. Switching to Pipes means we just get to see that extra processing happen and increase the time.

500 blog pages built:
- Before Pipes - ~30 seconds
- With Pipes - ~40 seconds

I think it's actually a pretty tolerable difference when compared, and the benefits of editing with Pipes features in place might be a good trade for this.

3. **Node Module installation** - This is currently unavoidable, but updating the README with the npm `--save-dev` option a little might help. I'd add something like this:

> Some npm packages are required. Install them in your site directory (not in the theme).
>`npm init -y` creates a quick default package.json file for storing dependencies (only run command if you don't already have this file)
>`npm install @babel/cli @babel/core @babel/preset-env browserslist clipboard cssnano postcss-cli postcss-import postcss-mixins postcss-nested postcss-preset-env postcss-url --save-dev`
> The **--save-dev** option adds these all to your package.json. In the future, a simple `npm install` will install all packages from that file.
> Add the `node_modules` folder to your site's `.gitignore` if you haven't already.

These steps did help me streamline my installation process a little. You might write it differently, though.

**My Opinion:** I think your update to use Pipes might be... fine, honestly. I wasn't quite sure of the changes at first since I didn't know what to expect, but finding out that what we're seeing might be **normal and not much of an issue** has brought me around to thinking that perhaps transitioning to Pipes is alright. I think it's just a matter of managing user expectations and the setup process to make things as smooth as possible.

**Side note:** I did run across this comment in the [Zen theme repo](https://github.com/frjo/hugo-theme-zen#the-hugo-zen-theme) --
> Sass is processed with Hugo pipes. To make using npm optional I have added the stylesheets from the excellent sass plugin typey directly to the theme.
It makes me wonder what they mean by making npm 'optional'. I didn't understand it. It might be worth checking out. It might be a red herring.

Anyway, this is all your call. I'm now on board with the change, but the old way was also fine with me. As long as it's running haha. Thanks for reading all my junk. Cheers, mate.

**Comment by gdmka** [comment]
Allow me to chime in. Couple years back i've used Hugo with this excellent team and i felt very productive.
Right now, being unaware of the amount of features inside the Hugo itself, i feel like my attempt to build a quick and clean blog fails. 
@panr does the look and feel of the theme should be identical to https://hugo-hello-friend.now.sh/ after all the setup process is done according to the guideline?
 
This is as much as i get with current setup process obtained from here https://themes.gohugo.io/hugo-theme-hello-friend/ 
<img width="915" alt="Screen Shot 2020-08-30 at 23 36 59" src="https://user-images.githubusercontent.com/1773275/91668968-96c14f80-eb00-11ea-975f-09b4708270c0.png">

Now, you know better how to carry on with it, but is there a **legacy**  solution that just works (the webpack one). What specific commit should i revert to to get productive again ?

**Comment by panr** [comment]
Hey @aormsby Webpack version is back ;-) Everything should work as before version 2. Let me know if everything is OK with the latest update.

**Comment by aormsby** [comment]
Cool beans. I saw some of those other issues - looks like you had your hands full for a bit!

I'll be sure to check and see if things are working for me with the latest. I never merged the updates before, so I think I'm a bit behind. The last thing I remember looking at was the cover image figure issue (#186), and I'll let you know if I spot anything else. Thanks, man. :)
