### ISSUE TITLE
function "babel" not defined when deploying on Netlify

### ISSUE THREAD

**Issue by iahmed0199** [panr/hugo-theme-hello-friend#189]
> First of all, the site works fine on the localhost, and when I upload it manually to Netlify it gives me "Page not Found" message and that means it deployed fine.

The problem here is that I upload my site files on Github so it can be automatically deployed with each push request, but deployment fails at footer.html file specifically line 16 where it says **babel not defined**.

Here's the log for further details
```
8:32:15 AM: ┌─────────────────────────────┐
8:32:15 AM: │        Netlify Build        │
8:32:15 AM: └─────────────────────────────┘
8:32:15 AM: ❯ Version
8:32:15 AM:   @netlify/build 3.3.0
8:32:15 AM: ❯ Flags
8:32:15 AM:   deployId: 5f3e18e491faed2a0caacfb9
8:32:15 AM:   mode: buildbot
8:32:15 AM: ❯ Current directory
8:32:15 AM:   /opt/build/repo
8:32:15 AM: ❯ Config file
8:32:15 AM:   No config file was defined: using default values.
8:32:15 AM: ❯ Context
8:32:15 AM:   production
8:32:15 AM: ​
8:32:15 AM: ┌───────────────────────────────────┐
8:32:15 AM: │ 1. Build command from Netlify app │
8:32:15 AM: └───────────────────────────────────┘
8:32:15 AM: ​
8:32:15 AM: $ hugo --gc --minify
8:32:15 AM: Error: "/opt/build/repo/themes/hello-friend/layouts/partials/footer.html:16:1": parse failed: template: partials/footer.html:16: function "babel" not defined
8:32:15 AM: ​
8:32:15 AM: ┌─────────────────────────────┐
8:32:15 AM: │   "build.command" failed    │
8:32:15 AM: └─────────────────────────────┘
8:32:15 AM: ​
8:32:15 AM:   Error message
8:32:15 AM:   Command failed with exit code 255: hugo --gc --minify
8:32:15 AM: ​
8:32:15 AM:   Error location
8:32:15 AM:   In Build command from Netlify app:
8:32:15 AM:   hugo --gc --minify
8:32:15 AM: ​
8:32:15 AM:   Resolved config
8:32:15 AM:   build:
8:32:15 AM:     command: hugo --gc --minify
8:32:15 AM:     commandOrigin: ui
8:32:15 AM:     publish: /opt/build/repo/public
```

**Comment by rmoralesdelgado** [comment]
Having the same problem here. Tried also on AWS Amplify and including the `yarn add -D ...` command but nothing.

**Comment by panr** [comment]
I thought that switching to the Hugo Pipes will be a good move, but suddenly it turned out that this causes more problems... I'll switch back to Webpack soon. Maybe this weekend, please be patient and sorry for any inconvenience 🙏 .

**Comment by panr** [comment]
Meanwhile, checking to this commit (https://github.com/panr/hugo-theme-hello-friend/commit/005e78d86cf4ee5babde47876d4950eb628bd9f8) should bring you back the old instance with Webpack. Treat this as a hotfix for a couple of days...

**Comment by rmoralesdelgado** [comment]
Thanks a lot for your reply! I tried the hotfix and works like a charm for both Netlify and AWS Amplify. I think that at least for these platforms (static web hosting/deploying) it is a good idea to keep using Webpack.

Again, thanks a lot for your help! :)

**Comment by panr** [comment]
@rmoralesdelgado the theme just has been updated and Webpack is back ;-) Let me know if it works for you 🙏

**Comment by rmoralesdelgado** [comment]
@panr just deployed (on Netlify) with the latest update and works perfectly. Thank you so much 😃
