### ISSUE TITLE
Linkrot in README

### ISSUE THREAD

**Issue by jhabdas** [panr/hugo-theme-hello-friend#19]
The following line:

> Check the original theme license for additional licensing information.

Contains a link. That link is broken. All forks containing that link will also be broken. You probably don't need that line though as the X11 license is [fairly](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) self-explanatory.

**Comment by panr** [comment]
Thanks, I've fixed the link ;-)

**Comment by jhabdas** [comment]
Thank you kind sir! (:
