### ISSUE TITLE
Dark mode flashing issue

### ISSUE THREAD

**Issue by derbalkon** [panr/hugo-theme-hello-friend#190]
Hi, thanks for making this theme!

Recently I encountered a "dark mode flashing" issue with this theme — a white screen would show up for a brief moment after refreshing or switching articles. 

I'm now using a slow speed network and this problem seems to be much more obvious than what I have experienced in a high speed network environment. So I guess maybe it is due to that JavaScript is often executed after CSS, and also the HTML is generated long before it reaches the user's device.

Also, I can always reproduce this problem on Safari, but less frequent on Chrome.

**Comment by FishionYu** [comment]
Me too

**Comment by panr** [comment]
Have you updated the theme recently? I wonder if it's related to changes introduced in version 2.

**Comment by derbalkon** [comment]
> Have you updated the theme recently?

No I haven't and this issue has existed before the version 2 initiated actually.

**Comment by panr** [comment]
Hmm... by default the theme is pre-rendered by Hugo engine, so if you configured the `defaultTheme ` in `config.toml/yml` file, you shouldn't have flashes even on slow speed net. BUT it can happen **when you change the theme manually** by clicking the icon. Then the theme selector starts to operate via javascript, so yes — this could cause the issue.

**Comment by panr** [comment]
Also:

- do we talk about the production version of your site? 
- do you have devtools opened during the tests?
- could you give the link to your site?

**Comment by derbalkon** [comment]
> BUT it can happen **when you change the theme manually** by clicking the icon.
> * do we talk about the production version of your site?
> * could you give the link to your site?

I'm talking about the demo site actually, it already has this problem even before I click the toggle button.
I've reworked the dark mode on my own site and it has a completely different logic from the demo, so it's probably not much of a reference.

> * do you have devtools opened during the tests?

I'm afraid not. I even tested it under private mode without any extensions on different devices.
The thing is, this issue usually happens on Safari for macOS, rarely on Safari for iOS, or other Chromium browser. I'm now not really sure if this is related to browser itself. If you want to take a look, I exported a timeline record from devtool on Safari for macOS and I'll attach here. It happened at the fourth attempt:

<details><summary>timeline record</summary>

[hugo-hello-friend.now.sh-recording.zip](https://github.com/panr/hugo-theme-hello-friend/files/5182507/hugo-hello-friend.now.sh-recording.zip)

</details>

**Comment by panr** [comment]
I can't figure it out. I see the flashing only when I have devtools open on Safari. But not only on the demo, but for all sites I tested. My guess is that this is something related to the Safari itself... Also I don't see this on Safari 14 (Preview).

**Comment by derbalkon** [comment]
> Also I don't see this on Safari 14 (Preview).

Turns out it is indeed related to Safari 13.... Upgrade to Safari 14 today and everything is fine now. Thanks for reminding me of this.
