### ISSUE TITLE
Theme not carried to other pages and posts

### ISSUE THREAD

**Issue by siddharthaxroy** [panr/hugo-theme-hello-friend#199]
Hello,

The theme works perfectly for all pages and posts when deployed on my machine. However, when I deploy it using Netlify (https://srorg.netlify.app/), the theme only works for the home page, but not for any others.

Any ideas on why this is? 

Many thanks,
Sid

PS: Brilliant theme, by the way.

**Comment by panr** [comment]
Huh, thanks for reporting that. I'll look at this as soon as I can 🙏

**Comment by panr** [comment]
Don't know why, but you have generated relative paths to the resources while they should be absolute (missing `/` at the beginning). Look here https://github.com/siddharthaxroy/srorg/blob/master/public/about/index.html#L20

**Comment by siddharthaxroy** [comment]
Thanks Radek! I used this repo to deploy the site on Netlify: https://github.com/siddharthaxroy/test/ Not the other one you linked to. Will recheck. The final website is here: www.siddhartharoy.org

**Comment by panr** [comment]
This is something related to the resources for sure. When you inspect the console or network tab in your browser you'll see this:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/1303365/92529318-94f73a80-f22a-11ea-9ab1-4cbb329e194d.png">

**Comment by panr** [comment]
@siddharthaxroy what about this line https://github.com/siddharthaxroy/test/blob/master/config.toml#L1? It looks like a typo for me 🤔

**Comment by siddharthaxroy** [comment]
Brilliant! Cannot believe it was that simple. That was a leftover code from a different theme. Fixed it! Again, so very grateful for your beautiful work.

**Comment by panr** [comment]
Glad we figured it out, I was worried that I blew something up with the latest update 😬 😅
