### ISSUE TITLE
Footer breaks

### ISSUE THREAD

**Issue by colemanrob** [panr/hugo-theme-hello-friend#2]
Footer breaks when you assign a value to copyright in the config.toml

**Comment by panr** [comment]
@colemanrob Can you add a screenshot of this bug? When you add your own `copyright` value in config.toml, footer should change and show only what you provide instead of generic footer.

**Comment by colemanrob** [comment]
Oh I see - then it's working as intended.  I thought the `copyright` value would only change the *Theme created by panr 2018*.  When it removed the entire footer i thought it was broken.

Thanks for the great work on this theme, its a beauty!

**Comment by panr** [comment]
@colemanrob Thanks! I designed it to work like this because people often delete theme credits and they put their own ones instead.
