### ISSUE TITLE
Summary not displayed

### ISSUE THREAD

**Issue by cmlnet** [panr/hugo-theme-hello-friend#203]
It seems there is a bug in how summaries of posts are displayed in index.html and lists.html. The bug was described in #100 and #127. Both times with the suggestion to use `Description` insted of `<!--more-->` in the posts.

The reason why `<!--more-->`does not work seems to be that `markdownify` is called on `.Summary`. Removing `markdownify`fixes the problem and the summary is called properly, maybe because markdown is already parsed.

I created an according pull request.

**Comment by panr** [comment]
Huh, that's interesting. I'll check your PR later. Thanks for raising it up! 👍
