### ISSUE TITLE
Hugo internal templates not picking up "cover" image for social?

### ISSUE THREAD

**Issue by shinytoyrobots** [panr/hugo-theme-hello-friend#205]
According to Hugo documentation, the internal templates for open graph/twitter should fallback with;

> hugo searches for image page resources with feature, cover, or thumbnail in their name. 

This doesn't seem to occur with setting the cover image in the page front matter. Have to specifically set;

`images:`
`- post-cover.png`

In order for any image thumbnail to be set for og or twitter.

Anyone else have this problem, and would it be an issue with this theme or an issue with the Hugo internal template?

**Comment by aormsby** [comment]
I was confused about this a while back. Some things about the way Hugo finds those images can be unclear. Something quick you can check - are your cover images in the same directory as the markdown file? Or are they nested in another directory? Moving all my cover images adjacent to the markdown file fixed it for me.

If that doesn't work, I might be able to help if you could provide more info about your setup. :)
