### ISSUE TITLE
[Question] How to achieve this effect ？

### ISSUE THREAD

**Issue by opfanswyx** [panr/hugo-theme-hello-friend#209]
Thank you for your great theme!

How to achieve this effect in the DEMO - [https://hugo-hello-friend.now.sh/](https://hugo-hello-friend.now.sh/) ？

![image](https://user-images.githubusercontent.com/20237214/93657104-33bd3b80-fa62-11ea-9d4c-174d24ac048f.png)

**Comment by panr** [comment]
You need to create `_index.md` directly in the `content` dir (or any section directory — you can read more about this in Hugo docs) with:

```
+++
framed = true
+++
```
as frontmatter and a content you want to place there below.

![image](https://user-images.githubusercontent.com/1303365/93662949-489ace80-fa64-11ea-99ed-3ddb3689b83c.png)

**Comment by opfanswyx** [comment]
Thank you very much！
