### ISSUE TITLE
CSS code line duplicated

### ISSUE THREAD

**Issue by ahuk** [panr/hugo-theme-hello-friend#22]
```
<link rel="stylesheet" href="/assets/style.css">
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source+Code+Pro' rel='stylesheet' type='text/css'>
{{ partial "inject.stylesheet.html" . }}
```

Line 1 and 3.

**Comment by panr** [comment]
Yeah, I've spotted it this weekend. (1st) should be in (3rd) place as a `/style.css` to override theme fixed styles for someone who doesn't want to rebuild the whole theme. I'll fix that soon 👌

**Comment by panr** [comment]
@ahuk fixed
