### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by alexdelli** [panr/hugo-theme-hello-friend#229]
Sorry for the question, but i don't know how to implement google analytics.
I insert the google analytics ID in config file, and than?
I have to move the analytics.html in another place?
thank you

p.s.: this is not an issue..... this is a help request :)

**Comment by dinko-pehar** [comment]
You can add Google Analytics by adding [tracking id in config file](https://gohugo.io/templates/internal/#configure-google-analytics) and including Google Analytics [internal template](https://gohugo.io/templates/internal/#use-the-google-analytics-template) in `layouts/partials/extended_head.html` [1](https://github.com/panr/hugo-theme-hello-friend#add-ons)
