### ISSUE TITLE
Index page renders without post

### ISSUE THREAD

**Issue by onedrawingperday** [panr/hugo-theme-hello-friend#23]
Hello @panr 

I just tested your theme with the Build Script. Thank you for fixing the content of `/showcase/`

However now the homepage renders empty.

The culprit is due to commit https://github.com/panr/hugo-theme-hello-friend/commit/b0dfb769d18fae502066b09abf17dacdbc6519f3

You have made it so that the parameter `contentTypeName = "post"` is required in the `config.toml` of the Example Site but you haven't defined it there so the Paginator Pages range renders empty now.

Can you look into fixing this?

Thanks

cc: @digitalcraftsman

**Comment by panr** [comment]
@onedrawingperday fixed it (I hope so)! Thanks for noticing it ;-) f48f16c8505583a038ad7c798673b69287ed1b5a.

**Comment by onedrawingperday** [comment]
@panr  Thanks for fixing it.

@digitalcraftsman the themes at the Hugo repo need to be updated whenever you can.

**Comment by onedrawingperday** [comment]
Actually this applies to your other theme.

Sorry I mixed the themes up. I'm opening another issue in the Termonal theme repo.

**Comment by panr** [comment]
@onedrawingperday oh... so for the `exampleSite` I should use `post`, right? If so, I've fixed it for **Terminal** theme and also fix every absolute paths 😛 https://github.com/panr/hugo-theme-terminal/commit/6c68bd63ae30b4e19a33a69a0a80bc2cc3eaa22b

I'm fixing these things for **Hello Friend** right now!

**Comment by panr** [comment]
@onedrawingperday OK, we're good to go with both themes! 😎

**Comment by digitalcraftsman** [comment]
> @digitalcraftsman the themes at the Hugo repo need to be updated whenever you can.

I did this a moment ago.
