### ISSUE TITLE
Line width

### ISSUE THREAD

**Issue by robertdiab** [panr/hugo-theme-hello-friend#235]
Hi again folks, 

I'm wondering how to shrink the line width -- of both headings and paragraphs, but nothing else.

I tried adding the following code to the 'body' element in my style.css file:

```
max-width: 710px;
margin: auto
```

This shortens the line-length of text, but it also shortens the banner at the top, which I want to avoid. I can't find where to tweak this elsewhere in the code -- or how to do it in my style sheet.

Any ideas would be much appreciated!

Thank you, 

Robert

**Comment by panr** [comment]
You can add those styles to `.post` element directly or `ul.posts` as a container, but there might be some issues with images, so you need to keep an eye on this too ;-)

**Comment by gongqij** [comment]
the follow css config not work：
`
max-width: 900px;
margin: auto
`
The line width seems to default to 800, which can only be shortened and not increased.
how to increase the line width？
