### ISSUE TITLE
head does not consider baseUrl for stylesheets

### ISSUE THREAD

**Issue by llauren** [panr/hugo-theme-hello-friend#25]
When serving the site from a path (like https://llauren.gitlab.io/kalla-mej-efraim/), the page won't render correctly, since `layouts/partials/head.html` tries to load [`/assets/style.css`](https://github.com/panr/hugo-theme-hello-friend/blob/bf0f5f5bce2b28b965b2836fe01be3415e221fe6/layouts/partials/head.html#L9) and [`/style.css`](https://github.com/panr/hugo-theme-hello-friend/blob/bf0f5f5bce2b28b965b2836fe01be3415e221fe6/layouts/partials/head.html#L12) directly without taking the baseUrl into account.

I suggest inserting `{{ $.Site.BaseURL }}` in front of the two stylesheet urls.

Apart from that, it's a really neat looking theme and i hope to be using it!

**Comment by panr** [comment]
Yes, I think you're right. Previously I suggested to use:

```
canonifyURLs: true
relativeURLs: true
``` 

...but I think your solution is better. There's even PR for that — — https://github.com/panr/hugo-theme-hello-friend/pull/24/commits/c8e49f331f31d66d3b5d63839747c7185d2531b2, I'll merge it ;-)
