### ISSUE TITLE
Code within single backticks getting converted to upper-case

### ISSUE THREAD

**Issue by iDuronto** [panr/hugo-theme-hello-friend#251]
Hi, first of all thanks for this great theme. Just a small issue, it looks like anything declared between triple backticks are rendered correctly (issue #3). But, anything declared between single backticks are converted to uppercase.

![](https://user-images.githubusercontent.com/33091912/130634540-cfa792cb-4944-48af-aaa8-c44f9975b332.png)

**Comment by iDuronto** [comment]
Okay, I just validated this, and looks like this issue is persistent on Linux (both Chrome and Firefox) only! For android mobile browsers, everything renders correctly, On Windows systems too it renders correctly.

**Comment by iDuronto** [comment]
Any clue whats going on @panr? :)

**Comment by smantic** [comment]
no idea what the problem is, I was able to resolve by adding 
```
code { 
    font-feature-settings: initial;
}
```
to `static/style.css`

**Comment by panr** [comment]
Oh, now I see, that I in fact did the fix, but only for code blocks 🤦 https://github.com/panr/hugo-theme-hello-friend/commit/a9a3e1a8f4917ee98142bff908a7bca888f0081f

Thanks for the hint, I will fix it right away ;-)
