### ISSUE TITLE
Site not working properly

### ISSUE THREAD

**Issue by abhinav031** [panr/hugo-theme-hello-friend#253]
![Screenshot_2021-09-04-52_1251x836](https://user-images.githubusercontent.com/73749351/132100528-e54b36ba-82cb-4f2c-99e0-8d006f02f40d.png)
doesnt look right

**Comment by panr** [comment]
Hmm.. it looks like you are trying to run my other theme: Terminal instead of this one 🤔

**Comment by abhinav031** [comment]
> Hmm.. it looks like you are trying to run my other theme: `Terminal`, instead of this one 🤔

No, but the problem seems to be gone now and the site works just fine.

**Comment by panr** [comment]
I'm glad to hear that 🙌
