### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by alexdelli** [panr/hugo-theme-hello-friend#257]
Hi all
I have this security alerts from Dependabot.
How can I fix ?
This is due to Hello friend theme?
thank you

![image](https://user-images.githubusercontent.com/6674409/137864204-3ec5faea-472b-410f-a5f6-95d099c99154.png)

**Comment by panr** [comment]
I'm working on it!

**Comment by panr** [comment]
Just updated the packages and added dependabot config to do weekly checks ;-)
