### ISSUE TITLE
Feature Request: Archives Page 

### ISSUE THREAD

**Issue by wieueberall** [panr/hugo-theme-hello-friend#26]
### Feature: Archives Page

I think it would be great having some sort of a archives page provided by the theme, so it'll be much easier to search for a specific post.

### Possible Implementation:

Create a Layout for the archives page in `layout/defaults/archives.html` so it can be called by creating an `archives.md` in the content folder by setting `layout: "archives"` in the toml/yaml.

### Possible Solution:

Something like this:

```
{{ partial "head.html" . }}
    {{ partial "header.html" . }}

<main class="content" role="main">
    <div class="inner">
        {{ range (.Site.RegularPages.GroupByDate "2006") }}
            <h3 class="archive-year">{{ .Key }}</h3>

            <ul class="archive-list">
                {{ range (where .Pages "Type" "post") }}
                    <li>
                        {{ .PublishDate.Format "02 Jan" }}
                        -
                        <a href="{{ .RelPermalink }}">{{ .Title }}</a>
                    </li>
                {{ end }}
            </ul>
        {{ end }}
    </div>
</main>

{{ partial "footer.html" . }}
```

### Process:

Feel free to assign me to this issues if you want to implement an archives page or do it yourself if you feel comfortable with doing so.

**Comment by panr** [comment]
Hmm... I don't know if it's relevant to the theme 🤔 
You can create this page layout in your site/blog repo...

My goal was to have as few features as possible, because you can easily add your own layouts in Hugo 😊

**Comment by jhabdas** [comment]
Thanks to [Lookup Order](https://gohugo.io/templates/lookup-order/) it's, as @panr mentions, makes it relatively easy to use Block Templates to create things like [Custom Layouts](https://after-dark.habd.as/id/feature/custom-layouts/) with Hugo. But if there isn't a simple _hook_ (so to speak) for rendering a [Content View Template](https://gohugo.io/templates/views/) that might be a different story as those customizing could benefit.

**Comment by panr** [comment]
@wieueberall I'll consider it, because I've got your point 😎 I need some time to get it right 👍

**Comment by dsolito** [comment]
Yes please. An option to use a content view template is welcome.

**Comment by cobalto** [comment]
I think that fork nailed it:
https://themes.gohugo.io//theme/hugo-theme-hello-friend-ng/post/
![image](https://user-images.githubusercontent.com/1196314/54482174-247e8180-481e-11e9-8caf-8878acd5c4b4.png)

But I still prefer the original implementation overall cause some good features were lost (and others add) on the fork.

**Comment by jeremejazz** [comment]
@cobalto The forked theme hello-friend combined with **[hermit](https://github.com/Track3/hermit)**. There was an added archive page in exchange for the pagination and blog list

**Comment by panr** [comment]
Just added archive page ;-) Please see https://github.com/panr/hugo-theme-hello-friend#add-ons
