### ISSUE TITLE
The Font has changed a little bit, is it expected?

### ISSUE THREAD

**Issue by mathieu-benoit** [panr/hugo-theme-hello-friend#269]
Before the latest version:
![image](https://user-images.githubusercontent.com/11720844/140565224-fd5c8f3d-4e96-4e4e-873d-e29008181dd8.png)
After the latest version:
![image](https://user-images.githubusercontent.com/11720844/140565241-7e0e1ebd-cc73-45ff-abb3-aa178d20f5ff.png)

What I mean by latest version is the new version which landed on Nov 1st 2021.

We could see few differences:
- letter `g` has changed
- text is quite in bold now
- characters are more condensed/close

**Comment by panr** [comment]
Oops, I'll check this out!

**Comment by panr** [comment]
Ugh... `css-loader` broke font rendering so I needed to switch it back to the previous version. Should be fine now ;-) Could you confirm?

**Comment by panr** [comment]
I made another fix, but this time I rewrote the webpack config.

**Comment by mathieu-benoit** [comment]
Much better, https://github.com/panr/hugo-theme-hello-friend/commit/34ce1500ecc620a876f9a10d2046ac5bd7d27d9b fixed the issue. I just integrated it, and everything is back to normal, thanks @panr! Closing that issue accordingly.

**Comment by panr** [comment]
Glad to hear that 👍
