### ISSUE TITLE
[Question] How to add a text box as you did in the demo page?

### ISSUE THREAD

**Issue by kneardhead** [panr/hugo-theme-hello-friend#270]
In the demo page, there's this block of text "**Hello there!** Welcome to the demo..." inside a box. 
I am new to Hugo sites, and I couldn't really implement such a text before the posts. I would appreciate your suggestions.

**Comment by KenHV** [comment]
Create `content/_index.md` with the following contents:
```
+++
framed = true
+++
```
You can add your desired text to the file.

**Comment by kneardhead** [comment]
@KenHV  thanks a lot, it works!
