### ISSUE TITLE
How we can add comment section in our post in this theme.?

### ISSUE THREAD

**Issue by m4xx101** [panr/hugo-theme-hello-friend#28]
I've used your theme for my website which I've built using Hugo but there's one problem for me that if I want to add a comment section in my post how can I achieve that.?

**Comment by panr** [comment]
Hi @m4xx101! Yes, now you can. I've just added content partial to `_default/single.html` theme layout.

So to "unlock" comments section, please create in your Hugo dir, `layouts/partials/comments.html` and insert `{{ template "_internal/disqus.html" . }}`. Then in `config.toml` add `disqusShortname = "yourdiscussshortname"`. Further info -> https://gohugo.io/content-management/comments/
