### ISSUE TITLE
Adding dark-mode versions of custom CSS

### ISSUE THREAD

**Issue by SpencerMichaels** [panr/hugo-theme-hello-friend#29]
I've just started using this theme for a website, and I'm adding a few custom elements. I'd like those elements to have dark- and light-mode theming, so in imitation of how `hello-friend`'s CSS does per-theme styling, I wrote my CSS elements like the following:

```
.element {
  color: var(--light-color);
  .dark-theme & {
    color: var(--dark-color);
  }
}
```

However, this doesn't have any effect: anything styled in this way, if they're my _own_ CSS classes, only ever use the light mode colors. I've tried a few different variants of this, but I'm pretty unfamiliar with CSS, so I haven't gotten anywhere so far. Presumably there are some other requirements with regards to the parents hierarchy of elements styled like this. What exactly do I need to do to give my custom CSS classes dark-mode-specific styling?

**Comment by panr** [comment]
@SpencerMichaels Hmm... this should work... Are you adding this to `/static/style.css` (you have to create it)? This is the only way right now to override or add custom styles 🤔

**Comment by SpencerMichaels** [comment]
Ah, no, I'm adding my own CSS and then including it into the page with `<link>` tags overriding HTML files in `/layouts/partial`. I could fork the theme and rebuild it to make these modifications, then.

Out of curiosity, why doesn't what I did work? My understanding is that this all gets lumped into the same static file upon building anyway, so it's weird that only the content of `/static/style.css` can use dark mode.

**Comment by panr** [comment]
Ok, I’ll check it 👌🏻

**Comment by panr** [comment]
> Ah, no, I'm adding my own CSS and then including it into the page with `<link>` tags overriding HTML files in `/layouts/partial`.

@SpencerMichaels which partial you're overriding?

**Comment by SpencerMichaels** [comment]
I overrode `header.html` and added the `<link>` tags right at the top. I see now that all the other CSS includes are done in `head.html`; maybe overriding that would have worked, but I'm not sure. Yesterday I forked the theme and made my changes directly to it, and that definitely makes my dark-theme CSS work as expected.

**Comment by panr** [comment]
Hmm... just added `<link>` inside `header.html` (in HTML5 it's "body-ok") and... in this newly added css file I can use color variables 🤔

**Comment by panr** [comment]
Hi @SpencerMichaels, any updates on this issue?

**Comment by aormsby** [comment]
I'm also running into this issue where the additional `.dark-theme & {}` segments aren't updating anything. It doesn't work when running the local web server (which may make sense) OR when I build and deploy to my site.

I'm doing as you said here --
> @SpencerMichaels Hmm... this should work... Are you adding this to `/static/style.css` (you have to create it)? This is the only way right now to override or add custom styles (without rebuilding the theme — when you fork it) 🤔

-- but only the normal data values hold firm in both light and dark. The secondary dark-theme data never kicks in.

Here's my extracted styling --
```css
.feedback-input {
    border: 1px solid;
    border-color: var(--dark-border-color);

    /* doesn't seem to do anything */
    .dark-theme & {
        border-color: var(--light-border-color);
    }
}
```
