### ISSUE TITLE
Sticky navbar

### ISSUE THREAD

**Issue by LITUATUI** [panr/hugo-theme-hello-friend#326]
Please add the option to make the navbar sticky, or make it default.

Thanks!

**Comment by bwc69151** [comment]
Just use CSS. Replace [this line](https://github.com/panr/hugo-theme-hello-friend/blob/master/assets/css/header.scss#L6) with the code below 
```
    position: sticky;
    top: 0;
```

**Comment by panr** [comment]
[bwc69151](https://github.com/bwc69151) is right. Just modify the code and you are good to go.
