### ISSUE TITLE
can't build my site due to a new error

### ISSUE THREAD

**Issue by dersavage** [panr/hugo-theme-hello-friend#329]
I get this message when I run `hugo` to build:

 render of "page" failed: "/Users/uxername/xolder/themes/hello-friend-ng/layouts/_default/baseof.html:4:11": execute of template failed: template: posts/single.html:4:11: executing "posts/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: html/template:partials/head.html:40:12: no such template "_internal/google_news.html"

Any ideas how to fix? Thanks.

**Comment by takeyamayuki** [comment]
I'm in the same situation.

**Comment by bwc69151** [comment]
Are you sure you are all using the latest version of the theme?

**Comment by vdougherty** [comment]
possibly the same issue, seems to be tied to: config.toml -  remove theme = "hello-friend" and i get a blank screen in the browser.  leave theme = "hello-friend"  and it produces the errors below.

Errors happened on a fresh install of hugo and theme. So yes, the most current theme on Hugo theme site.

Building sites … ERROR 2023/04/11 19:51:23 render of "taxonomyTerm" failed: execute of template failed: template: _default/terms.html:22:11: executing "footer" at <partial "footer.html" .>: error calling partial: "/home/doc/.blog/themes/hello-friend/layouts/partials/footer.html:15:41": execute of template failed: template: partials/footer.html:15:41: executing "partials/footer.html" at <js>: can't evaluate field Build in type string

ERROR 2023/04/11 19:51:23 render of "home" failed: execute of template failed: template: _default/index.html:22:11: executing "footer" at <partial "footer.html" .>: error calling partial: "/home/doc/.blog/themes/hello-friend/layouts/partials/footer.html:15:41": execute of template failed: template: partials/footer.html:15:41: executing "partials/footer.html" at <js>: can't evaluate field Build in type string
Built in 31 ms

Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: _default/terms.html:22:11: executing "footer" at <partial "footer.html" .>: error calling partial: "/home/doc/.blog/themes/hello-friend/layouts/partials/footer.html:15:41": execute of template failed: template: partials/footer.html:15:41: executing "partials/footer.html" at <js>: can't evaluate field Build in type string

**Comment by vdougherty** [comment]
which is a shame cause your theme rocks...

**Comment by takeyamayuki** [comment]
Since the theme I was using was the forked one, I am discussing it in [here](https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/416). Please refer to it.

**Comment by panr** [comment]
If you use Google News template then it has been removed recently: https://github.com/gohugoio/hugo/releases/tag/v0.111.0

It has nothing to do with the theme itself.
