### ISSUE TITLE
Change cursor color

### ISSUE THREAD

**Issue by usererror** [panr/hugo-theme-hello-friend#35]
I saw that it is possible to override CSS for the theme but I can't seem to override the bright pink cursor color. Is there an example of how to do so?

If it's not possible yet, would it be reasonable to add another `param` to set it?

**Comment by jhabdas** [comment]
CSS files for this theme reside in the `static` folder are generated using a Node-based build pipeline. The easiest and most foolproof way for you to customize the color is to:

Modify this:

https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/logo.css

Then regenerate the CSS using NPM and Node.

Unfortunately that may give you some problems down and you'll have to maintain your changes in a fork of the theme.

Fortunately Hugo's [lookup order](https://gohugo.io/templates/lookup-order/) will allow you to customize the [`logo.html`](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/logo.html) [template](https://gohugo.io/templates/) without forking or modifying theme source.

With a custom `logo.html` overriding the theme's version you could then customize it to add some inline CSS to set a `background` or `background-color` as shown here:

```go-html-template
{{/* some template stuff */}}
<style>
.logo__cursor {
  background-color: #ff00ff80;
}
</style>
```

Personally I'd go for the later for simplicity unless you plan on making more dramatic modifications, such as refactoring the theme to use [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction).

**Comment by jhabdas** [comment]
CSS files for this theme reside in the `static` folder are generated using a Node-based build pipeline. The easiest and most foolproof way for you to customize the color is to:

Modify this:

https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/logo.css

Then regenerate the CSS using NPM and Node.

Unfortunately that may give you some problems down as you'll have to maintain your changes in a fork or copy of the theme.

Fortunately Hugo's [lookup order](https://gohugo.io/templates/lookup-order/) will allow you to customize the [`logo.html`](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/logo.html) [template](https://gohugo.io/templates/) without forking or modifying theme source.

With a custom `logo.html` overriding the theme's version you could then customize it to add some inline CSS to set a `background` or `background-color` as shown here:

```go-html-template
{{/* some template stuff */}}
<style>
.logo__cursor {
  background-color: #ff00ff80;
}
</style>
```

Personally I'd go for the later for simplicity unless you plan on making more dramatic modifications, such as refactoring the theme to use [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction).

**Comment by jhabdas** [comment]
CSS files for this theme reside in the `static` folder are generated using a Node-based build pipeline. The easiest and most foolproof way for you to customize the color is to:

Modify this:

https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/logo.css

Then regenerate the CSS using NPM and Node.

Unfortunately that may give you some problems down as you'll have to maintain your changes in a fork or copy of the theme.

Fortunately Hugo's [lookup order](https://gohugo.io/templates/lookup-order/) will allow you to customize the [`logo.html`](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/logo.html) [template](https://gohugo.io/templates/) without forking or modifying theme source.

With a custom `logo.html` overriding the theme's version you could then customize it to add some inline CSS to set a `background` or `background-color` as shown here:

```go-html-template
{{/* some template stuff */}}
<style>
.logo__cursor {
  background-color: #ff00ff80;
}
</style>
```

Personally I'd go for the later for simplicity unless you plan on making more dramatic modifications, such as refactoring the theme to use [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction) or adding some CSS variables you could control from config.

**Comment by jhabdas** [comment]
CSS files for this theme reside in the `static` folder are generated using a Node-based build pipeline. The easiest and most foolproof way for you to customize the color is to:

Modify this:

https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/logo.css

Then regenerate the CSS using NPM and Node.

Unfortunately that may give you some problems down as you'll have to maintain your changes in a fork or copy of the theme.

Fortunately Hugo's [lookup order](https://gohugo.io/templates/lookup-order/) will allow you to customize the [`logo.html`](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/logo.html) [template](https://gohugo.io/templates/) without forking or modifying theme source.

With a custom `logo.html` overriding the theme's version you could then customize it to add some inline CSS to set a `background` or `background-color` as shown here:

```go-html-template
{{/* some template stuff */}}
<style>
.logo__cursor {
  background-color: #ff00ff80;
}
</style>
```

Personally I'd go for the later for simplicity unless you plan on making more dramatic modifications, such as refactoring the theme to use [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction) or adding CSS variables you could control from config.

**Comment by jhabdas** [comment]
CSS files for this theme reside in the `static` folder are generated using a Node-based build pipeline. The easiest and most foolproof way for you to customize the color is to:

Modify this:

https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/logo.css

Then regenerate the CSS using NPM and Node.

Unfortunately that may give you some problems down as you'll have to maintain your changes in a fork or copy of the theme.

Fortunately Hugo's [lookup order](https://gohugo.io/templates/lookup-order/) will allow you to customize the [`logo.html`](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/logo.html) [template](https://gohugo.io/templates/) without forking or modifying theme source.

With a custom `logo.html` overriding the theme's version you could then customize it to add some inline CSS to set a `background` or `background-color` as shown here:

```go-html-template
{{/* some template stuff */}}
<style>
.logo__cursor {
  background-color: #ff00ff80;
}
</style>
```

Personally I'd go for the later for simplicity unless you plan on making more dramatic modifications, such as refactoring the theme to use [Hugo Pipes](https://gohugo.io/hugo-pipes/introduction) or adding CSS variables controlled from config.

**Comment by panr** [comment]
@usererror you can also add `static/style.css` with the code above 😉 But it’s a good idea to add this param to config 👌🏻

**Comment by usererror** [comment]
Perfect! Adding the code block above to `static/style.css` did the trick. Thanks for the quick and detailed responses!
