### ISSUE TITLE
Null Error in Javascript

### ISSUE THREAD

**Issue by lxms** [panr/hugo-theme-hello-friend#38]
Hi, 

if only one menu item in main exists and config of _pages.showMenuItems_ is set to 1 
clicking inside the page generates a javascript error:
`[Error] TypeError: null is not an object (evaluating 'c.classList')
	(anonyme Funktion) (main.js:1:1706)`

This tracks back to _source/js/menus.js_ line 23 where **menuMore** is null
because no submenu element is rendered
 `{{ if gt (len $.Site.Menus.main) $.Site.Params.showMenuItems }}` in _menu.html_

One solution: Should a ` && menuMore ` after isMobile()

**Comment by panr** [comment]
@lxms thank you! Fixed it 👍
