### ISSUE TITLE
Cover Image Path

### ISSUE THREAD

**Issue by mpaepper** [panr/hugo-theme-hello-friend#39]
When I write a new post and I want to set a cover image for it, the image path needs to be complete from the root URL.
However, I think it would be more appropriate if the path would already be set to be the root of the current post, so you only specify the image relative to the post.
Let's make this more concrete:

Assume I have content/posts/a-great-new-post/index.md and my cover image is in content/posts/a-great-new-post/cover.png, then currently I need to set
cover: "posts/a-great-new-post/cover.png" 
to make it work.

I am afraid that this will be awkward in the future if you happen to change some URLs / paths of your posts and then the cover URL will be wrong.

What I am suggesting is to make the cover be relative to the blog post, so we would set it as:
cover: "cover.png"
in this case.

What do you think?

**Comment by pard68** [comment]
Pretty sure this is more a function of Hugo than this theme in particular. You would probably get a better answer over in gohugoio/hugi

**Comment by panr** [comment]
@mpaepper it's complicated ;-P Some people want to have relative path, other ones absolute... ¯\_(ツ)_/¯ 

What if you'll have separated `coverImage` fields? Eg. `absCoverImage` (with absolute path) and `relCoverImage` (with relative path)?

...or... a config param like `useCoverImageRelPaths`?

**Comment by mpaepper** [comment]
@panr I like the idea of being able to use both, so I implemented it such that one can decide whether to use the absolute cover like before or the relcover in each blog post.
This has the downside of duplicating the cover image code in the template.

Alternatively, we could also use a config parameter in the blog post itself. Hmm, that would probably be even nicer. I'll change it accordingly.

Then we have cover as before and if you change nothing, it stays the same, but in each post, we can set the useCoverRelative = true to change it to relative.

**Comment by mpaepper** [comment]
@panr  I improved the code now accordingly - it seems much cleaner and avoids the code duplication by using the boolean flag. I added some documentation to the README as well. Let me know what you think!

**Comment by panr** [comment]
Ok, merged! 😎
