### ISSUE TITLE
First line in code block not aligned with subsequent lines

### ISSUE THREAD

**Issue by johnj098** [panr/hugo-theme-hello-friend#4]
### Issue:
When using markdown such as the following for code blocks:

\```python
 print("Line one")
 print("Line two")
 print("Line three")
\```

The first line rendered is misaligned with the following lines. 

<img width="379" alt="capture - copy" src="https://user-images.githubusercontent.com/42505930/44305040-9f88c380-a333-11e8-97bc-2e1ecd4d54a0.PNG">

### Software Used:
OS - Windows 10
Browsers - Chrome 68 and Microsoft Edge
Hugo version - 0.46

**Comment by johnj098** [comment]
Looking through the CSS, it appears the culprit is the `margin: 0 2px;` declaration for the `code` selector.

The 2px left-right margin is normally fine for single markdown style inline code, but it is also applying the 2px margin to the first line within a multi-line code block.

Removing the `margin: 0 2px;` declaration fixes the problem but will sacrifice the 2px left-right margin for  inline code.

**Comment by panr** [comment]
Ok, I think I know how to fix it ;-)

**Comment by panr** [comment]
OK, I've fixed it ;-) Could you check it?

**Comment by johnj098** [comment]
Confirmed, it's fixed. Thanks for that and thanks for making this awesome theme!

**Comment by panr** [comment]
Thank you and you're welcome! ;-)
![proud](https://user-images.githubusercontent.com/1303365/44449210-c7a34b80-a5ed-11e8-9046-afade3fe8312.gif)
