### ISSUE TITLE
Your Theme Demo is 404 on the Hugo Site

### ISSUE THREAD

**Issue by onedrawingperday** [panr/hugo-theme-hello-friend#5]
The build script for the Hugo Themes site generates a demo for each theme by creating a theme folder named after the Git repository where the theme resides.

In your case the theme folder is called `hugo-theme-hello-friend`.

However Hugo is unable to find your theme and generate the demo because in the `config.toml` of your example site you have entered `theme = "hello-friend"`

Please change that line to `theme = "hugo-theme-hello-friend"` so that your demo can once again be generated on the Hugo Themes site.

Thank you!

**Comment by panr** [comment]
@onedrawingperday Oh... something has changed? I keep this part of `config.toml` file as it is from the beginning and there was no issue back then 😩 

I will change it 😉

**Comment by panr** [comment]
Ok, I've fixed it ;-)

**Comment by onedrawingperday** [comment]
@panr 

It seems that something has indeed changed with the Themes Site Build Script. 

I have also notified @digitalcraftsman about the 404 issue since there are other Theme Demos that are affected.

In any case your Demo will be live again once the Themes Site is published again.

Thank you for your understanding and sorry for the inconvenience.

**Comment by panr** [comment]
No problem ;-)
