### ISSUE TITLE
PDF file is not loading on the website even though it was uploaded

### ISSUE THREAD

**Issue by gabrielacaesar** [panr/hugo-theme-hello-friend#52]
Hey! I am using your theme to create [my portfolio website](https://www.gabrielacaesar.com). I uploaded some PDFs on ["static" folder in the repository](https://github.com/gabrielacaesar/blogdown2/tree/master/static). I am trying to link these PDFs to [my "courses" page](https://www.gabrielacaesar.com/courses/), but some of them are not loading. Is there a bug? Or am I doing something wrong? I am a beginner at programming language. Thank you.

**Comment by jeremejazz** [comment]
Your problem is not related to the theme. Static files are automatically included when the website is built. You need to run hugo again to allow hugo to copy the static files to the home. Please refer to the docs 
https://gohugo.io/content-management/static-files/
