### ISSUE TITLE
Utilize Hugo Internal Templates

### ISSUE THREAD

**Issue by jeremejazz** [panr/hugo-theme-hello-friend#54]
Hugo ships with a feature called [Internal Templates](https://gohugo.io/templates/internal/) that enables boilerplate for features such as 

- google analytics
- disqus (already suggested in comments partial) 
- open graph
- and twitter cards

As seen in the comments partial disqus short tag is suggested
Can we implement these built-in shortcodes instead? Thank you

**Comment by panr** [comment]
Good idea! 

![thereitis](https://user-images.githubusercontent.com/1303365/59525493-bd34a400-8ed6-11e9-8cd9-b0d8e4b51e56.gif)

https://github.com/panr/hugo-theme-hello-friend/commit/4a1b70019b5ef18d817b88f1ad359fce75de96a2

**Comment by jeremejazz** [comment]
awesome :smile_cat:
