### ISSUE TITLE
How to edit the theme

### ISSUE THREAD

**Issue by lebarde** [panr/hugo-theme-hello-friend#55]
Thank you for this great theme!

I have been diving into this theme to learn how to configure and edit it. It appears that I need to add my own colours (at least) and hence edit the postCSS files.

Do you see an easy way to do so without managing git branches? I would like to keep the theme up to date if it evolves in the future.

Thank you for your attention!

**Comment by panr** [comment]
Hmm... Unfortunately I don't see any other option than to fork the repo and keep updating it when new things or fixes will show up ;-(

**Comment by jeremejazz** [comment]
> I have been diving into this theme to learn how to configure and edit it. It appears that I need to add my own colours (at least) and hence edit the postCSS files. 

I think overriding [extended_head.html](https://github.com/panr/hugo-theme-hello-friend/blob/master/layouts/partials/extended_head.html) is your best option for now. Are you familiar with [lookup order](https://gohugo.io/templates/lookup-order/)? 

> Do you see an easy way to do so without managing git branches? I would like to keep the theme up to date if it evolves in the future.

Use git submodules it is recommended by the hugo team.
