### ISSUE TITLE
Why not use Hugo Pipes for PostCSS?

### ISSUE THREAD

**Issue by lebarde** [panr/hugo-theme-hello-friend#56]
Hello,
I can see that Hugo can handle PostCSS. In particular, this could help users to create an `assets/` directory that would be used before the theme specific `assets/` directory.

In particular, I assume that nodeJS would be mandatory. But that would not be the case of the is a way to create a condition (if postCSS is installed then compile, or else use the compiled CSS files).

What do you think of it?

**Comment by panr** [comment]
Because this theme was created before Hugo Pipes was introduced and I haven't changed that. Maybe I'll use this in my next theme ;-)
