### ISSUE TITLE
Changing logoText does not work as expected

### ISSUE THREAD

**Issue by marioblokland** [panr/hugo-theme-hello-friend#7]
If I add the logoText variable to my `config.toml` file like this:

```toml
[params.logo]
  logoText = "Mario"
```

It fully removes the logo text without inserting the new value. This means:

1. The `> Hello friend` text doesn't show up (which is expected)
2. The new value `Mario` doesn't show up either (which is not expected)
3. Thus, the space where the `> Hello friend` text was, is now just blank

If I remove the `logoText` variable from the `config.toml`, the `> Hello friend` shows up again.

**Comment by panr** [comment]
@marioblokland it should be fixed right now ;-) Could you confirm?

**Comment by marioblokland** [comment]
@panr Perfect! I can confirm that it now works. Thanks for this nice theme! :)

**Comment by panr** [comment]
You're welcome ;-)
