### ISSUE TITLE
Posts from future are not shown

### ISSUE THREAD

**Issue by MasterGroosha** [panr/hugo-theme-hello-friend#72]
Well, it took me nearly an hour to find out the reason.

I'm living in GMT+3, so at the moment of writing this issue it's 2019-07-05
However, "Hello-Friend" theme lives in GMT+0, so it's 2019-07-**04**! 

As a result, "a post from future" is missing. I have 2 questions now:
1) How can I disable hiding "posts from future"?
2) How can I customize "date" property so it will show hours:minutes and timezone?

**Comment by panr** [comment]
Hmm... it's strange, because it should render your local date. I'm GMT+2 and everything works fine 🤔 
Do you see this post on `localhost`?

**Comment by panr** [comment]
@MasterGroosha I think you have to add your date by passing a timezone, eg: `date = "2019-07-08T16:45:00+03:00"`.

Maybe someone else have a better solution? 🤔

**Comment by MasterGroosha** [comment]
I think passing timezone helped me (I did some experiments lately).
Will close the issue for now. Thank you for your help!
