### ISSUE TITLE
Posts list extends beyond screen on mobile, portrait mode

### ISSUE THREAD

**Issue by aormsby** [panr/hugo-theme-hello-friend#79]
Hey man, thanks for the awesome theme. I found a problem with the width of listed posts in the mobile display. In portrait mode, they extend beyond the edges of the screen left and right. My quick fix was to add this to my `/static/style.css` file --

```
.posts {
    width: 100%;
}
```
I figured this would be the simplest solution to maintain the full width list but still limit the bounds.

Normally, I'd work this into your theme css somewhere and toss it into a simple pull request, but I'm unsure where it should go (perhaps main.css?) and how best to re-build and submit for you. I'm rather unfamiliar with this level of css styling and the related tools you've used (such as yarn which I don't know how to use at all).

Your guidance on how to best prepare and submit this request here would be _awesome_. Thanks, man.

**Comment by panr** [comment]
Hmm... could you attach any screenshot with the bug? I can't reproduce it on my setup 🤔

**Comment by aormsby** [comment]
From my phone, without my css addition. As the excerpt text gets wider and takes up more space, it spreads the posts container beyond the edge of my screen. (That said, it seems my fix may not be doing what I thought it was anymore. I'll continue looking into this as well when I have time.)

![Screenshot_20190819-022630](https://user-images.githubusercontent.com/1312251/63229316-6c6c5f00-c229-11e9-904e-eafed5e614e2.png)

**Comment by jcalabres** [comment]
Same problem here.

**Comment by jcalabres** [comment]
Seems to be a good solution. @panr do you want I do a commit? 

Thank you,
Joan.

**Comment by panr** [comment]
Huh, it's odd... Could you test https://hugo-hello-friend.now.sh on your devices and let me know if this site is also buggy?

I've just tested this site on Safari, Chrome (in mobile view) and also on iPhone X (and don't have any Android phone 😢) and everything works fine 🤔

**Comment by panr** [comment]
And @jcalabres if you want to, please add PR with your fix (posts: 100%), but please do it here: https://github.com/panr/hugo-theme-hello-friend/blob/master/source/css/post.css#L1 (before `.post`)

**Comment by jcalabres** [comment]
Hello @panr, https://hugo-hello-friend.now.sh is working good with my iPhone7 (lol).

**Comment by panr** [comment]
Anyone reproduces this bug? 🤔

**Comment by aormsby** [comment]
Hey guys, sorry I haven't followed up on this. I've been busy with other things. To make a long story short, I figured out the issue was caused by the first chunk of content in one of my test posts being a huge code block. I guess code block data is unusable as preview content since it didn't display correctly AND it then caused the posts column to extend beyond the edges of my screen.

Everything works TOTALLY FINE when I put some normal text up front in the post. Sorry for not noticing that detail before. I feel like I could've seen that quicker if I'd had the chance to look at it further. Unless you want to look into displaying code data in the post previews, I'd support closing this issue.

Thanks for your patience. Great theme. I look forward to getting my blog running with it. :)

**Comment by kevinmachstudio** [comment]
@aormsby i got the error that you got, but i can't seem to get it working. What do you mean when you said "put some normal text up front in the post"

**Comment by aormsby** [comment]
If I remember correctly, my issue was that I had a big fenced code block as the first item in my markdown file. For whatever reason, that wouldn't be properly displayed following the preview page's CSS. Just as a guess - perhaps it couldn't be properly read as markdown? When I just started my file with plain text (after front matter), things went back to normal. The post summary was automatically grabbed, and I had no display problems. I never figured it out then, but I haven't really needed to since.

If you throw up a sample file or image, I'd be happy to take a quick look at your issue and see if it's similar.

**Comment by kevinmachstudio** [comment]
seems like it happened because i had text right after putting a link in the sentence, which messed up the markdown, i took the text out after that and it worked
