### ISSUE TITLE
Can't get Open Graph to work

### ISSUE THREAD

**Issue by Fastidious** [panr/hugo-theme-hello-friend#80]
Just pulled the theme. Added to a post the following on the YAML:
```
date: "2019-07-27T18:38:42-04:00"
title: "A title"
description: "A description."
cover: "/resources/a-title-cover-image.png"
image:
  - "/resources/a-title-cover-image.png"
```
The meta tags show:
```
[…]
<meta name="twitter:image" content="http://example.com/" />
[…]
<meta property="og:image" content="http://example.com/" />
```
It is also not grabbing the `description` and `title` from YAML, but the one from the `config.toml`.

What am I doing wrong?

**Comment by panr** [comment]
Did you wrap front matter in: 
```
---
// your code
---
```
?

Just tested YAML syntax on my own setup and it works fine 🤔

**Comment by panr** [comment]
Oh... I see that in your example you're using `image` tag, but you should `images` (as I mentioned on Twitter, it's an array / list of items)

**Comment by Fastidious** [comment]
@panr I have tried both ways. Real YAML:
```
---
date: "2019-04-25T18:38:42-04:00"
title: "I Am Sorry I Was Late"
description: "Sadly, despite my best efforts, I was ten minutes late. Please forgive me, Mrs. Lamorte."
cover: "/resources/2019-04-25-i-am-sorry-i-was-late.png"
images:
  - "/resources/2019-04-25-i-am-sorry-i-was-late.png"
categories:
  - personal
tags:
  - kent
  - images
---
```

Render snippet:
```
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="http://localhost:1313/"/>

<meta name="twitter:title" content="Site Name"/>
<meta name="twitter:description" content="Blog of a carbon based life-form, as unique as everyone else"/>



<meta property="og:title" content="Site Name" />
<meta property="og:description" content="Blog of a carbon based life-form, as unique as everyone else" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://localhost:1313/" />

<meta property="og:image" content="http://localhost:1313/" />

<meta property="og:updated_time" content="2019-07-28T16:56:28+00:00" /><meta property="og:site_name" content="Site Name" />
```

Notice that the description and title are not being used either. In this case, `Site Name`, and `Blog of a carbon based life-form, as unique as everyone else` are on the `config.toml`, but they should have been overwritten by `YAML` entries.

**Comment by panr** [comment]
Strange... it should work out of box...

**Comment by Fastidious** [comment]
I forgot to add I am using `Hugo v0.56`.

**Comment by panr** [comment]
I really don't know what's going on with your setup, but I updated Hugo to 56.1 (latest), with this front matter:

```
---
title: "Test"
date: "2019-07-08T16:45:00+02:00"
author: "Lorem Ipsum"
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec interdum metus. Aenean rutrum ligula sodales ex auctor, sed tempus dui mollis. Curabitur ipsum dui, aliquet nec commodo at, tristique eget ante."
images:
  - "img/hello.jpg"
---
```

my `<head>` looks like this:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/1303365/62083788-0e66e000-b258-11e9-9aab-62aa0f0feac7.png">

**Comment by Fastidious** [comment]
@panr how your `config.toml` looks like?

**Comment by Fastidious** [comment]
@panr I am an idiot. I was looking at the source of the post, while paginated! (which will never work) 🤦🏻‍♂️ Single post works are intended. Sorry for the waste of time, off I go to kick myself.

**Comment by panr** [comment]
I'm glad it works 😅
