### ISSUE TITLE
How to edit 404 page?

### ISSUE THREAD

**Issue by MasterGroosha** [panr/hugo-theme-hello-friend#83]
Maybe I'm missing something, but "404" page looks completely different from my other pages, it even uses "default" title instead of my own defined in config.toml.

**Comment by thomasjsn** [comment]
This theme doesn't have a 404 page, but [adding your own is easy!](https://gohugo.io/templates/404/)

**Comment by panr** [comment]
I should add this 404 template, I know 😓

**Comment by MasterGroosha** [comment]
@thomasjsn Thank you, I will check this guide later!
@panr Thank you for this awesome theme!

**Comment by panr** [comment]
You're welcome 🙌🏻
