### ISSUE TITLE
Front page broken with hugo 0.57.0

### ISSUE THREAD

**Issue by breucode** [panr/hugo-theme-hello-friend#86]
Preconditions:
Blog with one post

After upgrading to hugo 0.57.0, the front page showed the post caption, but not the summary. After clicking on "Read more", a new page opened under posts/, which looks like the proper front page from hugo 0.56.3.

One of these fixed issues could cause the problem: https://github.com/gohugoio/hugo/issues/6153 or https://github.com/gohugoio/hugo/issues/6154

**Comment by panr** [comment]
Thanks! I'll look at this issue soon 🙏

**Comment by panr** [comment]
I've fixed it in the same way like @wilsandbrink did in https://github.com/panr/hugo-theme-terminal/pull/74

Let me know if it works. I don't have 0.57.0 yet, because the latest version of Hugo on Brew is 0.56.3.

**Comment by breucode** [comment]
@panr Yes, that fixed it. Thank you for the quick fix and for the nice theme :).
