### ISSUE TITLE
Tag filtering broken with latest commit

### ISSUE THREAD

**Issue by thomasjsn** [panr/hugo-theme-hello-friend#87]
Commit 7427cfa3b47404c835423f4f085b564720b642c3 breaks tag filtering, all posts are shown also on `tags/` pages. Verified that it works correctly by undoing this commit.

Tested on Hugo version 0.56.3 and 0.57.2.

**Comment by panr** [comment]
@thomasjsn thanks for catching that. I'll look at this issue soon!

**Comment by panr** [comment]
@thomasjsn should be fine now 😬 Let me know if it works!

**Comment by thomasjsn** [comment]
@panr Yeah, that seems to have fixed it :)

**Comment by panr** [comment]
Good to hear that ;-)
