### ISSUE TITLE
git submodule add ....but show this below:

### ISSUE THREAD

**Issue by LGTMXD** [panr/hugo-theme-hello-friend#89]
hugo server
Building sites … ERROR 2019/08/29 15:51:05 render of "taxonomyTerm" failed: "/data/data/com.termux/files/home/123/themes/hello-friend/layouts/_default/list.html:10:50": execute of template failed: template: _default/list.html:10:50: executing "main" at <$PageContext.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
Total in 32 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/data/data/com.termux/files/home/123/themes/hello-friend/layouts/_default/list.html:10:50": execute of template failed: template: _default/list.html:10:50: executing "main" at <$PageContext.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState

**Comment by panr** [comment]
@LGTMXD what version of Hugo do you have? Could you try to update to the latest?🤔

**Comment by LGTMXD** [comment]
> @LGTMXD what version of Hugo do you have? Could you try to update to the latest?
yeah,i just now update to latest hugo version.its okay! thanks. @panr
