### ISSUE TITLE
`**` in markdown seems not work with Chinese and another issue report

### ISSUE THREAD

**Issue by kingcos** [panr/hugo-theme-hello-friend#90]
Thanks for your new theme! I like it a lot~

1. `**` in markdown seems not work with Chinese.

Source markdown: `我相信，**只有勇敢的面对问题的人，才能真正解决问题**。`. But I cannot figure out which is important from my eyes:

<img width="432" alt="Screen Shot 2019-08-30 at 9 05 42 PM" src="https://user-images.githubusercontent.com/10249989/64022991-efff4780-cb69-11e9-9317-ea3d814042f1.png">

The page in picture is https://maimieng.com/about/.

2. I insert a JSON code block, but when I publish it remote, its style seems not same as it showed on the local server.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Local File",
      "type": "Ruby",
      "request": "launch",
      "program": "${workspaceRoot}/${fileBasename}"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/10249989/64023305-93e8f300-cb6a-11e9-9f19-773f483c3d95.png)

The page in picture above is here: https://maimieng.com/posts/2019/coding_with_vs_code/

And this is the correct style from local server (with `hugo server -D`):

![image](https://user-images.githubusercontent.com/10249989/64023362-ba0e9300-cb6a-11e9-8509-49488cd987c8.png)

**Comment by kingcos** [comment]
Update:

When I tried update my local Hugo's version (0.55.0 to 0.57.2), the style seems as same as the online one (I'm using CI running `Hugo` commands). And what's more I find the reason. The code block conflicts with the list `-` above. Because I test it without `-` lines above code block.

So this could be an issue of Hugo? Or some issue of the lib which provide Mardown functions?

**Comment by panr** [comment]
`<strong>` works fine, and in chinese I see that default font (at least on my machine) is PingFang SC not Inter (this my default font for the theme).

I set it up to be more thick (600) than by default (400) and bold font has value of 800, so with PingFang SC difference is slightly visible... 

When I switch back default font weight to 400 (by disabling styles in `body`), you can see that `<strong>` works.

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/1303365/64040529-93962b00-cb5d-11e9-8c2e-66131a058ce6.png">

--

But with the second issue, I don't know what happened, but if you updated Hugo to the latest version and everything is fine, that's good ;-) Also minimum version for the theme is 0.57.0 after Hugo recent updates.

**Comment by kingcos** [comment]
@panr 
Thanks a lot. I write the styles in `style.css` and it works fine now.

About the second issue, it seems Hugo's issue, so I submitted to them. The truth is the latest version of Hugo is not working, but lower version works fine. 😅

Thanks for your amazing theme. I used the terminal before, and I use hello-friend now~
