### ISSUE TITLE
Unable to create dropdown menu

### ISSUE THREAD

**Issue by wojciehm** [panr/hugo-theme-hello-friend#92]
Hi. 

I abslotuely love this theme and you are doing a great job. 

I was wondering if this theme support drop down menus.

This is the code I am trying to implement
```    
[[languages.en.menu.main]]
        identifier = "sponsors"
        name = "Blog Sponsors"
        URL = "#"
        Weight = 1.0
      [[languages.en.menu.main]]
        name = "Veeam"
        parent = "sponsors"
        URL = "/sponsors/veeam.md"
        Weight = 1.0 
      [[languages.en.menu.main]]
        Name = "Vembu"
        parent = "sponsors"
        URL = "/sponsors/vembu.md"
        Weight = 2.0```

**Comment by panr** [comment]
Hi @wojciehm (czesc!) 😉 

You can only "transform" navigation into a dropdown menu by configuring how many items you would like to see — https://github.com/panr/hugo-theme-hello-friend#how-to-configure

In config you have this:

```
  [params]
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
```

So by using this and `weight` you can add "additional" dropdown menu to you navigation.

Let me know if this is what you're looking for ;-)

**Comment by wojciehm** [comment]
Hej.

Thanks a lot for explanation. As I love the theme I don't want to switch to other one I will stick to 

```
showMenuItems = 0

Do you plan to introduce drop-down menus in the future?

Cheers
Wojciech

**Comment by panr** [comment]
> As I love the theme I don't want to switch to other one

🤩

> Do you plan to introduce drop-down menus in the future?

After what you said above I think I have no choice 😅 I'll let you know when it's ready 👍🏻

**Comment by wojciehm** [comment]
Where do I donate? ;)

**Comment by panr** [comment]
There's no such place 🙈

**Comment by wojciehm** [comment]
I'll wait for the updates :)

**Comment by Perangelot** [comment]
Your theme is awesome! Nonetheless, we're still waiting for that update <3
