### ISSUE TITLE
Active page indicator on menu nav and logo

### ISSUE THREAD

**Issue by arvchristos** [panr/hugo-theme-hello-friend#99]
Hello and thank you for the magnificent minimal theme,

Is it in your plans to implement an active page indicator for current page on menu nav and logo? I have implemented it for my personal site as you can see here:

[arvchristos personal site](https://arvchristos.github.io)

As you can see, if the current page is home I choose to change the color of main logo while if it's one of the other pages I underline the nav item.

Please ping me if you can see this feature added in the main theme.

Thanks Again and keep up the quality work!!

**Comment by panr** [comment]
Will do!
